---
# tasks file for kuma
- name: Pull Uptime Kuma Docker image
  docker_image:
    name: louislam/uptime-kuma
    source: pull

- name: Run Uptime Kuma container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    published_ports:
      - "3000:3000"




