- hosts: localhost
  tasks:
    - name: Alert developer on Telegram
      telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: 642027926
          text: "The backend_cpp deployment is started."
          parse_mode: "markdown"
          disable_web_page_preview: true
          disable_notification: false