---
- hosts: localhost
  become: yes
  tasks: 
    - name: Building portfolio image and pushing to dockerhub
      community.docker.docker_image:
        build:
          path: ~/
        name: freddyt18/portfolio
        tag: latest
        push: true
        source: build