- hosts: localhost
  become: yes
  tasks: # Applying k8s manifests
    - name: Deploying the application
      shell: cd /var/lib/jenkins/tmp/devops-assignment/K8S/portfolio && sudo kubectl patch deployment portfolio -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  
    - name: Deploying the service
      community.kubernetes.k8s:
        state: present
        src: ~/tmp/devops-assignment/K8S/portfolio/service.yml
  
    - name: Deploying the issuer
      community.kubernetes.k8s:
        state: present
        src: ~/tmp/devops-assignment/K8S/portfolio/issuer.yml
  
    - name: Deploying the ingress controller
      community.kubernetes.k8s:
        state: present
        src: ~/tmp/devops-assignment/K8S/portfolio/ingress.yml
