- hosts: localhost
  become: yes
  tasks: # Applying k8s manifests
    - name: Deploying the application
      community.kubernetes.k8s:
        state: present
        src: ~/personal/devops-assignment/K8S/porfolio/deployment.yml
  
    - name: Deploying the service
      community.kubernetes.k8s:
        state: present
        src: ~/personal/devops-assignment/K8S/portfolio/service.yml
  
    - name: Deploying the issuer
      community.kubernetes.k8s:
        state: present
        src: ~/personal/devops-assignment/K8S/porfolio/issuer.yml
  
    - name: Deploying the ingress controller
      community.kubernetes.k8s:
        state: present
        src: ~/personal/devops-assignment/K8S/porfolio/ingress.yml
