---
# tasks file for kubectl
- name: Check if kubectl is installed
  shell: command -v kubectl
  register: kubectl_installed
  ignore_errors: true

- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: yes
  when: kubectl_installed.rc != 0

