---
# tasks file for droplet
- name: Create DigitalOcean droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: devops-assignment
    oauth_token: "{{ digital_ocean_token }}"
    size: s-2vcpu-4gb
    region: sgp1
    image: ubuntu-20-04-x64
    ssh_keys:
      - 4e:62:f4:03:40:21:eb:2c:4b:d4:53:f5:27:8c:35:a2
      - b9:4a:2a:24:cf:af:61:f6:e1:51:fc:00:3c:a0:2a:f3
  register: created_droplet

- name: Set created_droplet_public_ip variable
  set_fact:
    created_droplet_public_ip: "{{ created_droplet.data.ip_address }}"

- name: Point Cloudflare domain to created droplet
  community.general.cloudflare_dns:
    zone: pitou.live
    record: uptime
    type: A
    value: "{{ created_droplet_public_ip }}"
    account_email: "{{ cloudflare_email }}"
    api_token: "{{ cloudflare_api_token }}"
