---
# tasks file for droplet
- name: Create DigitalOcean droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: devops-assignment
    oauth_token: "{{ digital_ocean_token }}"
    size: s-2vcpu-4gb
    region: sgp1
    image: ubuntu-20-04-x64
    ssh_keys:
      - 1b:75:78:1d:e8:b6:68:a0:a2:9b:32:3c:f2:b6:34:77
      - b9:4a:2a:24:cf:af:61:f6:e1:51:fc:00:3c:a0:2a:f3
  register: created_droplet

- name: Printing out the data
  debug:
    msg: "{{ created_droplet }}"

- name: Set created_droplet_public_ip variable
  set_fact:
    created_droplet_public_ip: "{{ created_droplet.data.ip_address }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ created_droplet_public_ip }}"
    port: 22
    delay: 15

- name: Test SSH connection
  delegate_to: "{{ created_droplet_public_ip }}"
  command: echo "SSH connection successful"
  register: ssh_result

- name: Point Cloudflare domain to created droplet
  community.general.cloudflare_dns:
    zone: pitou.live
    record: uptime
    type: A
    value: "{{ created_droplet_public_ip }}"
    account_email: "{{ cloudflare_email }}"
    api_token: "{{ cloudflare_api_token }}"

- name: Edit hosts file
  blockinfile:
    path: /var/lib/jenkins/workspace/DevOps/jenkins_infra/Ansible/playbooks/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: '\[droplet\]'
    block: "{{ created_droplet_public_ip }}"


