---
- hosts: droplet
  roles:
    - kuma
  tasks:
    - name: Install sshpass
      apt:
        name: sshpass
        state: present

    - name: Copy SSL certs
      shell: |
        mkdir ~/pitou.live && sshpass -p '{{ devops_main }}' scp -o StrictHostKeyChecking=no -r root@{{ devops_ip }}:/etc/letsencrypt/live/pitou.live/ ~/pitou.live

    - name: Create Nginx configuration file
      copy:
        content: |
          server {
            listen 80;
            server_name uptime.pitou.live;
            return 301 https://$host$request_uri;
          }

          server {
            listen 443 ssl http2;
            # Remove '#' in the next line to enable IPv6
            # listen [::]:443 ssl http2;
            server_name sub.domain.com;
            ssl_certificate /root/pitou.live/pitou.live/fullchain.pem;
            ssl_certificate_key /root/pitou.live/pitou.live/privkey.pem;

            location / {
              proxy_set_header   X-Real-IP $remote_addr;
              proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header   Host $host;
              proxy_pass         http://localhost:3001/;
              proxy_http_version 1.1;
              proxy_set_header   Upgrade $http_upgrade;
              proxy_set_header   Connection "upgrade";
            }
          }
        dest: /etc/nginx/conf.d/uptime.pitou.live.conf

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
