---
- hosts: droplet
  roles:
    - kuma
  tasks:
    - name: Install sshpass
      apt:
        name: sshpass
        state: present

    - name: Copy SSL certs
      shell: sshpass -p '"{{ devops_main }}"' scp -r root@"{{ devops_ip }}":/etc/letsencrypt/live/pitou.live/ /etc/letsencrypt/live/pitou.live/

    - name: Create Nginx configuration file
      copy:
        content: |
          server {
            listen 80;
            server_name uptime.pitou.live;
            return 301 https://$host$request_uri;
          }

          server {
            listen 443 ssl;
            server_name uptime.pitou.live;

            ssl_certificate /etc/letsencrypt/live/pitou.live/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/pitou.live/privkey.pem;

            location / {
              proxy_pass http://localhost:3001;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          }
        dest: /etc/nginx/conf.d/uptime.pitou.live.conf

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
