---
- hosts: droplet
  tasks:
    - name: Installing doctl with snap
      shell: |
        snap install doctl
      become: yes

    - name: Create a DigitalOcean Kubernetes cluster
      community.digitalocean.digital_ocean_kubernetes:
        state: present
        oauth_token: "{{ digital_ocean_token }}"
        name: "devops-assignment-kuberenets-cluster"
        region: "sgp1"
        version: "latest"
        node_pools:
          - name: "worker-pool-1"
            size: "s-1vcpu-2gb"
            count: 2
            max-nodes: 2
        return_kubeconfig: yes
        wait_timeout: 600
      register: do_k8s_cluster

    - name: Connect to the Kubernetes cluster using doctl
      shell: |
        rm -rf ~/.kube && mkdir ~/.kube && sudo snap connect doctl:kube-config && doctl auth init -t {{ digital_ocean_token }} && doctl kubernetes cluster kubeconfig save {{ do_k8s_cluster.data.id }}
      when: do_k8s_cluster.changed
      become: yes

    - name: Testing the connection to the Kubernetes cluster
      shell: |
        kubectl get nodes
      when: do_k8s_cluster.changed
        