apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cpp
spec:
  replicas: 3
  minReadySeconds: 15
  selector:
    matchLabels:
      app: backend-cpp
  template:
    metadata:
      labels:
        app: backend-cpp
    spec:
      containers:
        - name: backend-cpp
          image: freddyt18/backend_cpp:latest
          imagePullPolicy: Always
          # resources: #default
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 18080
          volumeMounts:
            - name: vcpkg-tool
              mountPath: /vcpkg
          command: ["./app/linux-deploy.sh"]
      volumes:
        - name: vcpkg-tool
          hostPath:
            path: /root/tools/vcpkg