---
# tasks file for nginx
- name: Check if Nginx is installed
  shell: which nginx
  register: nginx_installed
  ignore_errors: true

- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: nginx_installed.rc != 0
  become: true
