---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: docker_already_installed == "no"

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
