---
# tasks file for github
- name: Configure .netrc file
  ansible.builtin.copy:
    content: |
      machine github.com
      login {{ github_username }}
      password {{ github_token }}
    dest: ~/.netrc
    mode: '0600'

- name: Set git user name
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git config user.name "{{ github_username }}"

- name: Set git user email
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git config user.email "{{ github_email }}"

- name: Set GitHub token
  ansible.builtin.set_fact:
    github_token: "{{ github_token }}"

- name: Add changes
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git add .

- name: Commit changes
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git commit -m "update"

- name: Change branch
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git checkout master

- name: Update branch
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git pull origin master

- name: Push changes
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git push origin master

