---
# tasks file for github
- name: Set git user name
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git config user.name "{{ github_username }}"

- name: Set git user email
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git config user.email "{{ github_email }}"

- name: Set GitHub token
  ansible.builtin.set_fact:
    github_token: "{{ github_token }}"

- name: Add changes
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git add .

- name: Commit changes
  ansible.builtin.command:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git commit -m "update"

- name: Push changes
  ansible.builtin.shell:
    chdir: /var/lib/jenkins/workspace/DevOps/jenkins_infra
    cmd: git push origin master
  environment:
    GIT_ASKPASS: /bin/echo
    GIT_USERNAME: "{{ github_token }}"
    GIT_PASSWORD: "{{ github_token }}"
